name       : perl-encode-locale
version    : 1.05
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/Encode-Locale-1.05.tar.gz : 176fa02771f542a4efb1dbc2a4c928e8f4391bf4078473bd6040d8f11adb0ec1
license    : GPL-2.0
summary    : Determine the locale encoding
description: |
    Determine the locale encoding
patterns   :
    - /usr/share/man
setup      : |
    perl Makefile.PL PREFIX=/usr INSTALLDIRS=vendor DESTDIR=%installroot%
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/lib/perl5/5.20.1
