name       : perl-encode-locale
version    : 1.05
release    : 10
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GA/GAAS/Encode-Locale-1.05.tar.gz : 176fa02771f542a4efb1dbc2a4c928e8f4391bf4078473bd6040d8f11adb0ec1
license    : Artistic-1.0-Perl
summary    : Determine the locale encoding
component  : programming.perl
description: |
    Determine the locale encoding
patterns   :
    - /usr/share/man
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
